name: 刷步数

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 22 * * *
  watch:
    types: started

jobs:
  build:
    # 关键修改：使用旧的Ubuntu版本
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: 开始
        run: |
          pip install requests
          pmode='${{ secrets.PMODE }}'
          pkey='${{ secrets.PKEY }}'
          user='${{ secrets.USER }}'
          pwd='${{ secrets.PWD }}'
          step='${{ secrets.STEP }}'

          python3 main.py ${pmode} ${pkey} ${user} ${pwd} ${step}
